# local and personal definitions

ifeq ($(OS),Windows_NT)
    #Windows stuff
SDK_ROOT := e:/Nordic/nRF5_SDK_15.2.0_9412b96
OUTPUT_DIRECTORY := _build_W
COM_PORT := COM8
else
    #Linux stuff
#SDK_ROOT := /mnt/e/Nordic/nRF5_SDK_15.1.0_a8c0c4d
SDK_ROOT := /mnt/e/Nordic/nRF5_SDK_15.2.0_9412b96
OUTPUT_DIRECTORY := _build_L
COM_PORT := /dev/ttyS8
endif
