# local and personal definitions

ifeq ($(OS),Windows_NT)
    #Windows stuff
SDK_ROOT := e:/Nordic/nRF5_SDK_16.0.0_98a08e2
OUTPUT_DIRECTORY := _build_W
COM_PORT := COM15
else
    #Linux stuff
SDK_ROOT := /mnt/e/Nordic/nRF5_SDK_16.0.0_98a08e2
OUTPUT_DIRECTORY := _build_L
COM_PORT := /dev/ttyS8
endif
